/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mercan' at '1/11/17 7:19 AM' with Gradle 2.14.1
 *
 * @author mercan, @date 1/11/17 7:19 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
